name: CMake ununtu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PWD_DIR: /home/runner
      CPPFLAGS: "-I/usr/include -I/usr/local/include -I/home/runner/hdf4/include -I/home/runner/stare/include -I/home/runner/hdfeos2/include"
      LDFLAGS: "-L/home/runner/hdf4/lib -L/home/runner/stare/lib -L/home/runner/hdfeos2/lib"
        
    steps:
    - uses: actions/checkout@v2
    - name: Installs
      run: |
        set -x
        sudo apt-get install netcdf-bin libnetcdf-dev doxygen graphviz wget gfortran libjpeg-dev libz-dev
    - name: cache-hdf4
      id: cache-hdf4
      uses: actions/cache@v2
      with:
        path: ~/hdf4
        key: hdf4-${{ runner.os }}-4.2.13

    - name: build-hdf4
      if: steps.cache-hdf4.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://support.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.gz &> /dev/null
        tar zxf hdf-4.2.13.tar.gz
        cd hdf-4.2.13
        ./configure --disable-netcdf --prefix=${PWD_DIR}/hdf4
        make all 
        sudo make install clean
        cd ..
    - name: cache-hdfeos2
      id: cache-hdfeos2
      uses: actions/cache@v2
      with:
        path: ~/hdfeos2
        key: hdfeos2-${{ runner.os }}-19v1

    - name: build-hdfeos2
      if: steps.cache-hdfeos2.outputs.cache-hit != 'true'
      run: |
        set -x
        wget https://github.com/OPENDAP/hyrax-dependencies/raw/master/downloads/HDF-EOS2.19v1.00.tar.Z &> /dev/null
        uncompress HDF-EOS2.19v1.00.tar.Z
        tar xvf HDF-EOS2.19v1.00.tar && ls -l
        cd hdfeos
        ./configure  --enable-install-include --prefix=${PWD_DIR}/hdfeos2
        make
        sudo make install
        cd ..
    - name: cache-stare
      id: cache-stare
      uses: actions/cache@v2
      with:
        path: ~/stare
        key: stare-${{ runner.os }}-0.16.7

    - name: build-stare
      if: steps.cache-stare.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/SpatioTemporal/STARE/archive/0.16.7-beta.tar.gz &> /dev/null
        tar zxf 0.16.7-beta.tar.gz
        cd STARE-0.16.7-beta/
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/stare ..
        make all
        sudo make install
        cd ../..

        
    - name: cmake
      run: |
        set -x
        mkdir build
        cd build
        nc-config --libs
        export LIBS=`nc-config --libs`
        export CXX_STANDARD_LIBRARIES=-lz        
#        cmake -DCMAKE_CXX_STANDARD_LIBRARIES="${CXX_STANDARD_LIBRARIES}" -DCMAKE_BUILD_TYPE=Debug --trace-source=test/CMakeLists.txt  -DCMAKE_PREFIX_PATH='/home/runner/hdf4;/home/runner/hdfeos2' -DSTARE_INCLUDE_DIR=~/stare/include -DSTARE_LIBRARY=~/stare/lib ..
#        make VERBOSE=1
#        make VERBOSE=1 test



